included:
  - AppHost
  - Modules/CashRunwayCorePackage/Sources
  - Sources
  - Tests

excluded:
  - Vendor
  - .build
  - "**/ReportingSecrets.generated.swift"

disabled_rules:
  - identifier_name
  - trailing_comma
  - static_over_final_class
  - unneeded_override
  - type_body_length
  - function_parameter_count
  - for_where
  - function_body_length
  - superfluous_disable_command
  - large_tuple
  - unused_enumerated
  - void_function_in_ternary
  - implicit_optional_initialization
  - private_over_fileprivate
  - redundant_discardable_let
  - optional_data_string_conversion
  - trailing_newline

line_length:
  warning: 300
  error: 300

file_length:
  warning: 2500
  error: 2500

function_body_length:
  warning: 100
  error: 200

function_parameter_count:
  warning: 5
  error: 10

large_tuple:
  warning: 3
  error: 5