#!/usr/bin/env swift
import Foundation

let projectRoot = URL(fileURLWithPath: CommandLine.arguments[0])
    .deletingLastPathComponent()
    .deletingLastPathComponent()

let exampleConfig = projectRoot.appendingPathComponent("AppHost/ReportingConfig.example.xcconfig")
let localConfig = projectRoot.appendingPathComponent("AppHost/ReportingConfig.local.xcconfig")
let generatedPaths = [
    projectRoot.appendingPathComponent("AppHost/AppReportingSecrets.generated.swift")
]

func parseConfig(_ url: URL) -> [String: String] {
    guard let contents = try? String(contentsOf: url, encoding: .utf8) else { return [:] }
    var values: [String: String] = [:]
    for line in contents.components(separatedBy: .newlines) {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty, !trimmed.hasPrefix("//") else { continue }
        guard let equalsIndex = trimmed.firstIndex(of: "=") else { continue }
        let key = String(trimmed[..<equalsIndex]).trimmingCharacters(in: .whitespaces)
        let value = String(trimmed[trimmed.index(after: equalsIndex)...]).trimmingCharacters(in: .whitespaces)
        values[key] = value
    }
    return values
}

var config = parseConfig(exampleConfig)
if FileManager.default.fileExists(atPath: localConfig.path) {
    config.merge(parseConfig(localConfig)) { _, new in new }
}

let secret = config["CASH_RUNWAY_REPORT_CLIENT_SECRET"] ?? ""
let isPlaceholder = secret.isEmpty || secret.contains("replace-with")

let obfuscationKey = Array("CashRunwayReportSecret".utf8)
let secretBytes = Array(secret.utf8)
let obfuscated = secretBytes.enumerated().map { index, byte in
    byte ^ obfuscationKey[index % obfuscationKey.count]
}
let hexBytes = obfuscated.map { "0x" + String(format: "%02x", $0) }.joined(separator: ", ")
let keyHex = obfuscationKey.map { "0x" + String(format: "%02x", $0) }.joined(separator: ", ")

let swiftSource = """
// Generated by Scripts/generate-reporting-secrets.swift. Do not edit manually.
// WARNING: If this file was generated with a real CASH_RUNWAY_REPORT_CLIENT_SECRET,
// do NOT commit it. The placeholder version committed in the repo uses isPlaceholder = true.
// swiftlint:disable all

import Foundation

enum AppReportingSecrets {
    static let isPlaceholder: Bool = \(isPlaceholder)

    static func clientSecret() -> String {
        let key: [UInt8] = [\(keyHex)]
        let obfuscated: [UInt8] = [\(hexBytes)]
        let bytes = obfuscated.enumerated().map { index, byte in
            byte ^ key[index % key.count]
        }
        return String(bytes: bytes, encoding: .utf8) ?? ""
    }
}
"""

for path in generatedPaths {
    try? FileManager.default.createDirectory(
        at: path.deletingLastPathComponent(),
        withIntermediateDirectories: true,
        attributes: nil
    )
    try swiftSource.write(to: path, atomically: true, encoding: .utf8)
}

print("Generated AppReportingSecrets.generated.swift (placeholder: \(isPlaceholder))")
