#!/usr/bin/env python3
"""
Generate Sources/CashRunwayCore/MCCCategoryMapping.swift from a curated table.

Only high-confidence per-MCC mappings belong here. Ambiguous service, retail,
financial, government, religious, and miscellaneous MCCs are intentionally
omitted so bank imports fall back to Other Expense instead of over-classifying.
"""
import argparse
import sys
from pathlib import Path

# fmt: off
MCC_TO_CATEGORY: dict[int, str] = {
    # Transportation
    4111: "Transport",  # Local/suburban commuter passenger transport
    4112: "Transport",  # Passenger railways
    4121: "Transport",  # Taxicabs and limousines
    4131: "Transport",  # Bus lines
    4814: "Utilities",  # Telecommunication services
    4784: "Transport",  # Tolls and bridge fees
    4789: "Transport",  # Passenger transportation services
    5541: "Transport",  # Service stations
    5542: "Transport",  # Automated fuel dispensers

    # Food and dining
    5411: "Groceries",    # Grocery stores and supermarkets
    5422: "Groceries",    # Meat provisioners
    5441: "Groceries",    # Candy, nut, and confectionery stores
    5451: "Groceries",    # Dairy product stores
    5462: "Groceries",    # Bakeries
    5499: "Groceries",    # Miscellaneous food stores
    5818: "Entertainment", # Digital goods: media, books, movies, and music
    5811: "Restaurants",  # Caterers
    5812: "Restaurants",  # Eating places and restaurants
    5813: "Restaurants",  # Drinking places
    5814: "Restaurants",  # Fast food restaurants
    5921: "Groceries",    # Package stores: beer, wine, and liquor

    # Health
    5122: "Health",  # Drug proprietaries and sundries
    5912: "Health",  # Drug stores and pharmacies
    8011: "Health",  # Doctors
    8021: "Health",  # Dentists and orthodontists
    8031: "Health",  # Osteopaths
    8041: "Health",  # Chiropractors
    8042: "Health",  # Optometrists and ophthalmologists
    8043: "Health",  # Opticians
    8049: "Health",  # Podiatrists and chiropodists
    8050: "Health",  # Nursing and personal care facilities
    8062: "Health",  # Hospitals
    8071: "Health",  # Medical and dental laboratories
    8099: "Health",  # Medical services

    # Education
    8211: "Education",  # Elementary and secondary schools
    8220: "Education",  # Colleges, universities, and professional schools
    8241: "Education",  # Correspondence schools
    8244: "Education",  # Business and secretarial schools
    8249: "Education",  # Vocational and trade schools
    8299: "Education",  # Schools and educational services

    # Shopping, housing, and education
    5211: "Housing",     # Lumber and building materials stores
    5310: "Shopping",    # Discount stores
    5399: "Shopping",    # Miscellaneous general merchandise
    5712: "Housing",     # Furniture and home furnishings stores
    5734: "Shopping",    # Computer software stores
    5942: "Education",   # Book stores
    5992: "Shopping",    # Florists

    # Travel and entertainment
    4411: "Travel",         # Cruise lines
    4511: "Travel",         # Airlines and air carriers
    7011: "Travel",         # Lodging, hotels, motels, resorts
    7512: "Travel",         # Automobile rental agency
    7832: "Entertainment",  # Motion picture theaters
    7841: "Entertainment",  # Video tape rental stores
    7911: "Entertainment",  # Dance halls, studios, and schools
    7922: "Entertainment",  # Theatrical producers and ticket agencies
    7929: "Entertainment",  # Bands, orchestras, and entertainers
    7932: "Entertainment",  # Billiard and pool establishments
    7933: "Entertainment",  # Bowling alleys
    7941: "Entertainment",  # Commercial sports
    7991: "Entertainment",  # Tourist attractions and exhibits
    7996: "Entertainment",  # Amusement parks
    7997: "Entertainment",  # Membership clubs: sports and recreation
    7999: "Entertainment",  # Recreation services
}
# fmt: on

def generate_swift(mapping: dict[int, str]) -> str:
    lines = [
        "import Foundation",
        "",
        "// Generated by Scripts/generate-mcc-mapping.py",
        "// Source: card-network MCC descriptions; category assignments are",
        "// intentionally curated per MCC and ambiguous codes are omitted.",
        "public enum MCCCategoryMapping {",
        "    public static func categoryName(for mcc: Int) -> String? {",
        "        lookup[mcc]",
        "    }",
        "",
        "    private static let lookup: [Int: String] = [",
    ]
    for code in sorted(mapping):
        escaped = mapping[code].replace('"', '\\"')
        lines.append(f'        {code}: "{escaped}",')
    lines.extend([
        "    ]",
        "}",
    ])
    return "\n".join(lines) + "\n"

def committed_path(repo_root: Path) -> Path:
    return repo_root / "Sources" / "CashRunwayCore" / "MCCCategoryMapping.swift"

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if committed output is stale")
    args = parser.parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    output_path = committed_path(repo_root)
    swift = generate_swift(MCC_TO_CATEGORY)
    if args.check:
        existing = output_path.read_text(encoding="utf-8")
        if existing != swift:
            print("Committed MCCCategoryMapping.swift is stale. Run Scripts/generate-mcc-mapping.py", file=sys.stderr)
            sys.exit(1)
        print("MCCCategoryMapping.swift is up to date.")
        return
    output_path.write_text(swift, encoding="utf-8")
    print(f"Wrote {len(MCC_TO_CATEGORY)} mappings to {output_path}")

if __name__ == "__main__":
    main()
